### ISSUE TITLE
Improve bot messages

### ISSUE THREAD

**Issue by ejayxyz** [agoraxyz/discord-runner#169]
## **Improvement**

Our discord bot messages feels a little bit awkward, and oldish style. We should improve every access related message, when we are sending any direct message to our users. 

Even we should implement this kind of message to everywhere, where we assigns a new role:
![image](https://user-images.githubusercontent.com/51904825/162516024-6e6bf0f2-65e7-4846-8341-447d935a69f0.png)

**Comment by Devidxyz** [comment]
Implemented with other features
